/* 직장인 대전 — 10-fighter roster (office archetypes), bilingual KO/EN */
(function () {
  "use strict";
  // hp: round HP · pw: damage multiplier · sp: move speed
  window.FIGHTERS = [
    {
      id: "boss",
      name: "김부장",
      nameEn: "Mgr. Kim",
      trait: "대머리·업무독촉",
      traitEn: "Bald · Nagger",
      art: "img/fighter_boss.png",
      battle: "img/fb_boss.png",
      attack: "img/fa_boss.png",
      skin: "#f0c8a0",
      hair: "bald",
      suit: "#2e4a7a",
      tie: "#c0392b",
      hp: 115,
      pw: 1.25,
      sp: 0.85,
      light: "서류철 잽",
      lightEn: "Folder jab",
      heavy: "결재판 강타",
      heavyEn: "Clipboard smash",
      special: { name: "서류 사자후·광풍", nameEn: "Paperwork Roar", type: "aoe", color: "#f4f6fb" },
      quote: "\"이거 언제까지 돼요?!\"",
      quoteEn: "\"When's this gonna be done?!\"",
      taunt: "\"자네, 야근 각오는 됐나?\"",
      tauntEn: "\"Ready to work overtime, kid?\"",
      ending:
        "김부장은 사내 격투대회 우승 트로피를 결재판 위에 올려두고 흡족해했다. 하지만 다음 날 아침, 트로피에도 포스트잇이 붙어 있었다. — '이거 반려. 다시.' 승리조차 반려당하는 남자, 그것이 부장이다.",
      endingEn:
        "Kim proudly set his championship trophy on his clipboard. But next morning, even the trophy had a sticky note: 'Rejected. Redo.' A man whose very victory gets sent back for revisions — that is a department manager.",
    },
    {
      id: "lee",
      name: "이대리",
      nameEn: "Lee",
      trait: "카페인 중독",
      traitEn: "Caffeine addict",
      art: "img/fighter_lee.png",
      battle: "img/fb_lee.png",
      attack: "img/fa_lee.png",
      skin: "#eac197",
      hair: "#3a2a18",
      suit: "#5b6472",
      tie: "#2b3a4a",
      hp: 100,
      pw: 1.0,
      sp: 1.1,
      light: "키보드 난타",
      lightEn: "Keyboard mash",
      heavy: "머그컵 스매시",
      heavyEn: "Mug smash",
      special: { name: "아메리카노 세례", nameEn: "Americano Shower", type: "projectile", color: "#5a3a1e" },
      quote: "\"카페인이 곧 나야.\"",
      quoteEn: "\"I AM caffeine.\"",
      taunt: "\"한 잔 하고 시작할까?\"",
      tauntEn: "\"One more cup before we start?\"",
      ending:
        "우승 상품은 1년치 원두. 이대리는 그 자리에서 전부 갈아 마셨고, 심장이 삼바를 추기 시작했다. 그날 이후 사내에서 이대리의 손떨림을 이길 자는 없었다.",
      endingEn:
        "The prize was a year's supply of coffee beans. Lee ground and drank them all on the spot, and his heart started dancing samba. From that day, no one in the company could out-jitter Lee.",
    },
    {
      id: "park",
      name: "박과장",
      nameEn: "Park",
      trait: "아부의 달인",
      traitEn: "Master flatterer",
      art: "img/fighter_park.png",
      battle: "img/fb_park.png",
      attack: "img/fa_park.png",
      skin: "#f0c8a0",
      hair: "#221a12",
      suit: "#8a7a52",
      tie: "#7a5a2a",
      hp: 100,
      pw: 1.05,
      sp: 1.0,
      light: "명함 슬래시",
      lightEn: "Business-card slash",
      heavy: "악수 압박",
      heavyEn: "Handshake crush",
      special: { name: "접대 폭탄주", nameEn: "Bomb Shot Combo", type: "lunge", color: "#ffd54a" },
      quote: "\"부장님 말씀이 맞습니다!\"",
      quoteEn: "\"You're absolutely right, sir!\"",
      taunt: "\"에이~ 살살 합시다, 우리가 남이야?\"",
      tauntEn: "\"C'mon, go easy — we're practically family!\"",
      ending:
        "박과장은 우승하자마자 심사위원 전원에게 명함을 돌렸다. '이 영광을 위원님들께.' 결국 그는 대회 MVP가 아니라 '올해의 처세왕'으로 특별상을 받았다. 실력보다 무서운 건 붙임성이었다.",
      endingEn:
        "The moment Park won, he handed his business card to every judge. 'This honor is yours, gentlemen.' In the end he got a special 'Office Politics King' award instead of MVP. Scarier than skill was his networking.",
    },
    {
      id: "choi",
      name: "최사원",
      nameEn: "Choi",
      trait: "열정 신입",
      traitEn: "Eager rookie",
      art: "img/fighter_choi.png",
      battle: "img/fb_choi.png",
      attack: "img/fa_choi.png",
      skin: "#f5d0a8",
      hair: "#101010",
      suit: "#7fb2e6",
      tie: "#274b6e",
      hp: 92,
      pw: 0.9,
      sp: 1.35,
      light: "열정 잽",
      lightEn: "Passion jab",
      heavy: "패기 훅",
      heavyEn: "Gutsy hook",
      special: { name: "오버타임 러시", nameEn: "Overtime Rush", type: "lunge", color: "#46e07a" },
      quote: "\"제가 하겠습니다!\"",
      quoteEn: "\"I'll do it!\"",
      taunt: "\"선배님, 한 수 배우겠습니다!\"",
      tauntEn: "\"Teach me something, senpai!\"",
      ending:
        "신입 최사원이 선배들을 모조리 꺾었다. 사무실은 발칵 뒤집혔고, 김부장은 조용히 그를 정직원으로 발령냈다. 최사원은 눈을 반짝이며 외쳤다. \"그럼 이제 진짜 야근인가요?!\" 아무도 대답하지 못했다.",
      endingEn:
        "Rookie Choi defeated every senior. The office was in uproar, and Kim quietly made him a full-time employee. Eyes sparkling, Choi shouted, \"So now it's REAL overtime?!\" No one could answer.",
    },
    {
      id: "jung",
      name: "정차장",
      nameEn: "Jung",
      trait: "라떼 꼰대",
      traitEn: "Boomer boss",
      art: "img/fighter_jung.png",
      battle: "img/fb_jung.png",
      attack: "img/fa_jung.png",
      skin: "#eac197",
      hair: "#b8b8bc",
      suit: "#6b4a2b",
      tie: "#4a2f18",
      hp: 108,
      pw: 1.1,
      sp: 0.9,
      light: "훈화 지적",
      lightEn: "Lecture jab",
      heavy: "결재 반려",
      heavyEn: "Rejection stamp",
      special: { name: "라떼는 음파", nameEn: "Back-In-My-Day Wave", type: "projectile", color: "#e7d3a1" },
      quote: "\"나 때는 말이야~\"",
      quoteEn: "\"Back in my day...\"",
      taunt: "\"요즘 것들은 맷집이 없어.\"",
      tauntEn: "\"Kids these days have no grit.\"",
      ending:
        "정차장은 우승 소감으로 40분짜리 훈화를 시작했다. \"나 때는 말이야, 대회도 없이…\" 관중은 하나둘 졸기 시작했고, 결국 정차장은 텅 빈 관중석 앞에서 홀로 우승을 만끽했다.",
      endingEn:
        "Jung began a 40-minute acceptance lecture. \"Back in my day, we didn't even have tournaments...\" One by one the crowd dozed off, and Jung ended up savoring his victory alone before empty seats.",
    },
    {
      id: "han",
      name: "한대리",
      nameEn: "Han",
      trait: "전산실 IT",
      traitEn: "IT dept",
      art: "img/fighter_han.png",
      battle: "img/fb_han.png",
      attack: "img/fa_han.png",
      skin: "#e9c39a",
      hair: "#1a1a24",
      suit: "#22303a",
      tie: "#43d9e6",
      hp: 96,
      pw: 1.0,
      sp: 1.15,
      light: "원격 클릭",
      lightEn: "Remote click",
      heavy: "랜선 채찍",
      heavyEn: "LAN-cable whip",
      special: { name: "서버 다운 EMP", nameEn: "Server-Down EMP", type: "aoe", color: "#43d9e6" },
      quote: "\"재부팅 해보셨어요?\"",
      quoteEn: "\"Have you tried rebooting?\"",
      taunt: "\"님 랙 걸린 듯? ㅋ\"",
      tauntEn: "\"You lagging, bro? lol\"",
      ending:
        "한대리는 우승과 동시에 대회 집계 서버를 해킹해 자신의 전적을 '무패 신화'로 박제했다. 아무도 반박할 수 없었다. 서버 관리자가 바로 그였으니까.",
      endingEn:
        "The moment he won, Han hacked the tournament server and immortalized his record as an 'undefeated legend.' No one could argue — he WAS the server admin.",
    },
    {
      id: "oh",
      name: "오팀장",
      nameEn: "Oh",
      trait: "워커홀릭",
      traitEn: "Workaholic",
      art: "img/fighter_oh.png",
      battle: "img/fb_oh.png",
      attack: "img/fa_oh.png",
      skin: "#f0c8a0",
      hair: "#2b2b33",
      suit: "#cfd6e3",
      tie: "#8a1111",
      hp: 104,
      pw: 1.1,
      sp: 1.0,
      light: "노트북 잽",
      lightEn: "Laptop jab",
      heavy: "야근 스매시",
      heavyEn: "Overtime smash",
      special: { name: "밤샘 오라", nameEn: "All-Nighter Aura", type: "aoe", color: "#b06bd9" },
      quote: "\"오늘 안에 끝냅시다.\"",
      quoteEn: "\"Let's finish it today.\"",
      taunt: "\"이 정도로 지치면 야근 못 해요.\"",
      tauntEn: "\"Tired already? Can't pull an all-nighter like that.\"",
      ending:
        "오팀장은 우승 트로피를 받아든 채 그대로 회의실로 향했다. \"자, 그럼 회고 미팅 잡죠.\" 새벽 4시, 형광등 아래 오팀장의 그림자만이 길게 늘어졌다. 그는 결코 퇴근하지 않는다.",
      endingEn:
        "Trophy in hand, Oh headed straight to the meeting room. \"Right, let's book a retrospective.\" At 4 AM, only Oh's shadow stretched under the fluorescent lights. He never, ever goes home.",
    },
    {
      id: "seo",
      name: "서주임",
      nameEn: "Seo",
      trait: "사내 헬창",
      traitEn: "Gym rat",
      art: "img/fighter_seo.png",
      battle: "img/fb_seo.png",
      attack: "img/fa_seo.png",
      skin: "#e0a878",
      hair: "#141414",
      suit: "#3a3f4a",
      tie: "#ff5db1",
      hp: 112,
      pw: 1.3,
      sp: 0.95,
      light: "프로틴 잽",
      lightEn: "Protein jab",
      heavy: "벤치프레스 훅",
      heavyEn: "Bench-press hook",
      special: { name: "데드리프트 슬램", nameEn: "Deadlift Slam", type: "lunge", color: "#ff5db1" },
      quote: "\"3세트만 더!\"",
      quoteEn: "\"Just three more sets!\"",
      taunt: "\"운동 안 하면 그렇게 됩니다, 선배님.\"",
      tauntEn: "\"Skip the gym and you end up like that, senior.\"",
      ending:
        "서주임은 우승 트로피를 덤벨 삼아 그 자리에서 20회 컬을 시작했다. \"이건 오늘 3대 500 중 준비운동이에요.\" 회사 헬스장은 그날부로 '서주임 전용관'이 되었다.",
      endingEn:
        "Seo used the trophy as a dumbbell and did 20 curls on the spot. \"This is just a warm-up for my daily lifts.\" From that day, the company gym became 'Seo's private studio.'",
    },
    {
      id: "yoon",
      name: "윤사원",
      nameEn: "Yoon",
      trait: "사내 인싸",
      traitEn: "Office influencer",
      art: "img/fighter_yoon.png",
      battle: "img/fb_yoon.png",
      attack: "img/fa_yoon.png",
      skin: "#f5d0a8",
      hair: "#3a2320",
      suit: "#ff8fb3",
      tie: "#d94f86",
      hp: 94,
      pw: 0.95,
      sp: 1.25,
      light: "셀카봉 찌르기",
      lightEn: "Selfie-stick poke",
      heavy: "인싸 하이파이브",
      heavyEn: "Popular high-five",
      special: { name: "회식 소환", nameEn: "Summon Company Dinner", type: "projectile", color: "#ffd54a" },
      quote: "\"이거 스토리각!\"",
      quoteEn: "\"This is SO going on my story!\"",
      taunt: "\"승부보다 인증샷이 먼저지~\"",
      tauntEn: "\"Selfie first, fight later~\"",
      ending:
        "윤사원의 우승 영상은 사내 메신저에서 조회수 10만을 돌파했다. 정작 본인은 트로피보다 '좋아요' 수에 더 감격했다. \"구독과 알림설정… 아 여긴 회사지.\"",
      endingEn:
        "Yoon's victory clip passed 100k views on the company messenger. He was more moved by the 'likes' than the trophy. \"Like and subscribe— oh wait, this is work.\"",
    },
    {
      id: "kang",
      name: "강이사",
      nameEn: "Dir. Kang",
      trait: "냉혈 임원",
      traitEn: "Cold executive",
      art: "img/fighter_kang.png",
      battle: "img/fb_kang.png",
      attack: "img/fa_kang.png",
      skin: "#eac197",
      hair: "#1a1a1a",
      suit: "#101018",
      tie: "#ffd54a",
      hp: 106,
      pw: 1.2,
      sp: 1.05,
      light: "지시봉 찌르기",
      lightEn: "Pointer stab",
      heavy: "결재 도장",
      heavyEn: "Approval stamp",
      special: { name: "구조조정 파이널", nameEn: "Restructuring Final", type: "projectile", color: "#ff2222" },
      quote: "\"자네, 정리 좀 하지.\"",
      quoteEn: "\"You. Get your affairs in order.\"",
      taunt: "\"이건 대회가 아니라, 평가야.\"",
      tauntEn: "\"This isn't a tournament. It's a performance review.\"",
      ending:
        "강이사는 우승컵을 내려다보며 서명 펜을 꺼냈다. \"수고했네. 그런데 말이야—\" 그가 서류에 도장을 찍자 대회 자체가 '비용 절감'을 이유로 폐지되었다. 정상에 오른 순간, 정상마저 구조조정된 것이다.",
      endingEn:
        "Kang looked down at the cup and drew his signing pen. \"Good work. But you see—\" As he stamped the document, the tournament itself was abolished for 'cost reduction.' The moment he reached the top, the top itself was restructured away.",
    },
  ];

  // Arcade ladder: order of opponents to climb; kang is always the final boss.
  window.LADDER = ["choi", "yoon", "lee", "park", "seo", "han", "jung", "oh", "boss", "kang"];
})();
